using MavenOperator.ImportJob.Models;
using MavenOperator.ImportJob.Services;
using System.Net.Http.Headers;
using System.Runtime.CompilerServices;
using System.Text;
using System.Text.Json;

namespace MavenOperator.ImportJob.Sources;

/// <summary>
/// Crawls a Reposilite instance via its REST API.
/// GET /api/maven/details/{repo}/{path} returns a directory listing.
/// GET /api/maven/repository/{repo}/{path} returns artifact bytes.
/// </summary>
public sealed class ReposiliteApiSource : IRepositorySource
{
    private readonly HttpClient _http;
    private readonly string _baseUrl;
    private readonly string _repository;
    private readonly ILogger<ReposiliteApiSource> _logger;

    private static readonly string[] ChecksumExtensions = [".md5", ".sha1", ".sha256", ".sha512"];
    private static readonly string[] SkipFileNames = ["maven-metadata.xml"];

    public ReposiliteApiSource(
        IHttpClientFactory httpFactory,
        string baseUrl,
        string repository,
        string? username,
        string? password,
        ILogger<ReposiliteApiSource> logger)
    {
        _http       = httpFactory.CreateClient("reposilite");
        _baseUrl    = baseUrl.TrimEnd('/');
        _repository = repository;
        _logger     = logger;

        if (!string.IsNullOrEmpty(username))
        {
            var creds = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{username}:{password}"));
            _http.DefaultRequestHeaders.Authorization = new AuthenticationHeaderValue("Basic", creds);
        }
    }

    public async IAsyncEnumerable<ArtifactDescriptor> CrawlAsync(
        ImportFilters filters,
        [EnumeratorCancellation] CancellationToken ct)
    {
        DateTimeOffset? since = filters.SinceTimestamp is { Length: > 0 } ts
            ? DateTimeOffset.Parse(ts)
            : null;

        var queue = new Queue<string>();
        queue.Enqueue("/");

        while (queue.Count > 0 && !ct.IsCancellationRequested)
        {
            var path = queue.Dequeue();
            var details = await FetchDetailsAsync(path, ct);
            if (details is null) continue;

            foreach (var entry in details.Files)
            {
                if (entry.Type == "DIRECTORY")
                {
                    queue.Enqueue($"{path.TrimEnd('/')}/{entry.Name}");
                    continue;
                }

                // Skip maven-metadata.xml (regenerated by operator)
                if (SkipFileNames.Any(s => entry.Name.Equals(s, StringComparison.OrdinalIgnoreCase)))
                    continue;

                // sinceTimestamp filter
                if (since.HasValue && entry.LastModified.HasValue && entry.LastModified < since)
                    continue;

                var relativePath = BuildRelativePath(path, entry.Name);

                // Group filter
                if (!FilterHelper.MatchesGroupFilters(relativePath, filters))
                    continue;

                _logger.LogDebug("Found artifact: {Path}", relativePath);

                yield return new ArtifactDescriptor
                {
                    RelativePath = relativePath,
                    SizeBytes    = entry.ContentLength,
                    LastModified = entry.LastModified,
                };
            }
        }
    }

    private async Task<ReposiliteDirectoryListing?> FetchDetailsAsync(string path, CancellationToken ct)
    {
        var url = $"{_baseUrl}/api/maven/details/{_repository}{path}";
        try
        {
            var response = await _http.GetAsync(url, ct);
            if (!response.IsSuccessStatusCode)
            {
                _logger.LogWarning("Failed to fetch listing at {Url}: {Status}", url, response.StatusCode);
                return null;
            }

            var json = await response.Content.ReadAsStringAsync(ct);
            return JsonSerializer.Deserialize<ReposiliteDirectoryListing>(json,
                new JsonSerializerOptions { PropertyNameCaseInsensitive = true });
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Error fetching listing at {Url}", url);
            return null;
        }
    }

    /// <summary>Downloads the artifact bytes for streaming to the sink.</summary>
    public async Task<Stream?> OpenStreamAsync(ArtifactDescriptor artifact, CancellationToken ct)
    {
        var url = $"{_baseUrl}/api/maven/repository/{_repository}/{artifact.RelativePath}";
        try
        {
            var response = await _http.GetAsync(url, HttpCompletionOption.ResponseHeadersRead, ct);
            response.EnsureSuccessStatusCode();
            return await response.Content.ReadAsStreamAsync(ct);
        }
        catch (Exception ex)
        {
            _logger.LogWarning(ex, "Error downloading {Path}", artifact.RelativePath);
            return null;
        }
    }

    private static string BuildRelativePath(string directoryPath, string fileName)
    {
        var dir = directoryPath.Trim('/');
        return string.IsNullOrEmpty(dir) ? fileName : $"{dir}/{fileName}";
    }

    private sealed class ReposiliteDirectoryListing
    {
        public List<ReposiliteFileEntry> Files { get; set; } = [];
    }

    private sealed class ReposiliteFileEntry
    {
        public string Name { get; set; } = string.Empty;
        public string Type { get; set; } = string.Empty;
        public long? ContentLength { get; set; }
        public DateTimeOffset? LastModified { get; set; }
    }
}

