apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "maven-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maven-operator.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "maven-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "maven-operator.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "maven-operator.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: operator
          image: {{ include "maven-operator.image" . }}
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          ports:
            - name: metrics
              containerPort: 9090
              protocol: TCP
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          env:
            - name: DOTNET_ENVIRONMENT
              value: Production
            - name: IMPORT_JOB_SERVICE_ACCOUNT_NAME
              value: {{ include "maven-operator.importJobServiceAccountName" . | quote }}
            - name: AUTH_PROXY_IMAGE
              value: {{ include "maven-operator.authProxyImage" . | quote }}
            - name: VIRTUAL_PROXY_IMAGE
              value: {{ include "maven-operator.virtualProxyImage" . | quote }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}

