AapiVersion: v1
kind: Service
metadata:
  name: {{ include "maven-operator.fullname" . }}-metrics
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maven-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: metrics
      port: 9090
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "maven-operator.selectorLabels" . | nindent 4 }}

