{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "maven-operator.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maven-operator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

{{- $operatorServiceAccountName := include "maven-operator.serviceAccountName" . -}}
{{- $importJobServiceAccountName := include "maven-operator.importJobServiceAccountName" . -}}
{{- if and .Values.importJob.serviceAccount.create (or (not .Values.serviceAccount.create) (ne $operatorServiceAccountName $importJobServiceAccountName)) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $importJobServiceAccountName }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "maven-operator.labels" . | nindent 4 }}
  {{- with .Values.importJob.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}

